# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - 1.1
    - 1.2
    - nightly
notifications:
    email: false

# .travis.yml codecov support is broken; see https://invenia/PkgTemplates.jl/issues/68
# codecov: true
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coverage.submit(process_folder());'
